<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '6',
    'typeid' => '0',
    'title' => '李水泳',
    'style' => '',
    'thumb' => 'http://sitemagic.oss-cn-beijing.aliyuncs.com//user/4075/upload/17-01-16/1484528970_pic.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.te.com/index.php?m=content&c=index&a=show&catid=6&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '0',
    'updatetime' => '1534340852',
    'hitsid' => 'c-1-3',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '李金秋',
    'style' => '',
    'thumb' => 'http://sitemagic.oss-cn-beijing.aliyuncs.com//user/4075/upload/16-12-22/1482368585_pic.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.te.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '0',
    'updatetime' => '1534340151',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '6',
    'typeid' => '0',
    'title' => '党天才',
    'style' => '',
    'thumb' => 'http://sitemagic.oss-cn-beijing.aliyuncs.com//user/4075/upload/17-01-16/1484531340_pic.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.te.com/index.php?m=content&c=index&a=show&catid=6&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '0',
    'updatetime' => '1534343997',
    'hitsid' => 'c-1-4',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '田亚洲',
    'style' => '',
    'thumb' => '/user/4075/upload/18-04-02/1522650931_7419_pic.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.te.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '0',
    'updatetime' => '1534340128',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'ttt',
    'style' => '',
    'thumb' => '',
    'keywords' => 'ttt',
    'description' => 'ttt',
    'posids' => '0',
    'url' => 'http://www.te.com/index.php?m=content&c=index&a=show&catid=6&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1534864197',
    'updatetime' => '1534864205',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>